[general]
# Original: LINES_COUNT_TO_READ = 1_000_000_000
LINES_COUNT_TO_READ = 1_000
APPROXIMATE_TRAIN_RATIO = 0.85

[als]
# Original: HYPER_N_EPOCH = 20
HYPER_N_EPOCH = 0 # Just want to revive the objects

# Original: HYPER_N_FACTOR = 10
HYPER_N_FACTOR = 10

HYPER_GAMMA = 0.01
HYPER_LAMBDA = 0.1
HYPER_TAU = 1
CHECKPOINT_FOLDER = "./artifacts/checkpoints/als"

[figures]
PLT_FIGURE_FOLDER = "./figures"
PLT_FIGURE_FORMAT = "svg"
