[general]
# Original: LINES_COUNT_TO_READ = 1_000_000
LINES_COUNT_TO_READ = 400 # 20_000_000
TRAIN_TEST_SPLIT_RATIO = 0.1

[als]
# Original: HYPER_N_EPOCH = 20
HYPER_N_EPOCH = 4

# Original: HYPER_N_FACTOR = 10
HYPER_N_FACTOR = 10

HYPER_GAMMA = 0.01
HYPER_LAMBDA = 0.1
HYPER_TAU = 1
CHECKPOINT_FOLDER = "./artifacts/checkpoints"

[figures]
PLT_FIGURE_FOLDER = "./figures"
PLT_FIGURE_FORMAT = "svg"
