name: Python CI/CD Workflow
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on: [push]

jobs:
  Python-Workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      # Step 4: Install dependencies using Poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install

      # Step 5: Run code style check with Black
      - name: Code Style Check with Black
        run: poetry run black --check .

      # Step 6: Compile Jupyter Notebook
      - name: Compile Jupyter Notebook
        run: |
          make compile
          echo "Jupyter Notebook compiled successfully."

      # Step 7: List files in the repository (debug step)
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
